# Scheduled workflow, with a manual option, to run the Cypress test that checks the
# store page.

name: Check Store

on:
  schedule:
    - cron:  '0,20,40 * * * *'
  workflow_dispatch:

jobs:
  cypress-run:
    name: Run Cypress test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true

  twilio-sms:
    name: 'Sending SMS Notification'
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: ${{ secrets.TWILIO_PHONE_NUMBER }}
          toPhoneNumber: ${{ secrets.PHONE_NUMBER }}
          message: 'The Stardew Valley board game is in stock'
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
